CREATE TABLE pets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    owner_name VARCHAR(255) NOT NULL
);

INSERT INTO pets (name, owner_name) VALUES ('Buddy', 'John Smith');
INSERT INTO pets (name, owner_name) VALUES ('Whiskers', 'Jane Doe');
INSERT INTO pets (name, owner_name) VALUES ('Max', 'Bob Johnson');